### ISSUE TITLE
Upstreaming

### ISSUE THREAD

**Issue by amezin** [matszpk/amdgpu-vega-hotspot#1]
Have you tried sending this patch to amd-gfx@lists.freedesktop.org ?

**Comment by matszpk** [comment]
This patch is not the official part of the AMDGPU driver. Some parts of this patch should be rewritten to be conformant with current AMDGPU driver architecture and structure. Same patch uses obsolete and deprecated structures and interfaces in an AMDGPU driver. Maybe, I will rewrite that patch and I will try to send this patch to mentioned mailing-list.

**Comment by amezin** [comment]
So AMD did it themselves https://cgit.freedesktop.org/~agd5f/linux/commit/?h=drm-next-5.2-wip&id=2bd99be1745d02b0e1d899dcc3e356d1d2b61dcf
